[project]
name = "zig-pypi"
version = "0"

requires-python = "~=3.7"
dependencies = [
  "wheel~=0.41.0",
]

[tool.pdm.dev-dependencies]
upload = ["twine"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
